stages:
    - build

build:
    stage: build
    image: rust:latest
    before_script:
        - rustup component add rust-src
        - cargo install cargo-xbuild
    script:
        - rustc --version && cargo --version && cargo xbuild --version
        - make
        - make DEBUG=n
    artifacts:
        expire_in: 1 week
        paths:
            - build/debug/oxerun-*.bin
            - build/release/oxerun-*.bin
